spring.application.name=notification-service
server.port=8100

spring.datasource.url=jdbc:postgresql://localhost:5432/notification-service
spring.datasource.username=postgres
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
